### ISSUE TITLE
Error in getting score

### ISSUE THREAD

**Issue by apresunreve** [WebFace260M/webface260m-iccv21-mfr#1]
Previously I submitted a few zip files and successfully got scores. Just now I switched to a new model and passed the test, but could not get scores from the system. I would like to know what was the cause.
Any suggestion is appreciated. 

Below is the error message:
-----------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/codalab/tmph4mOac/run/program/score.py", line 52, in 
    scores = get_score(input_dir)
  File "/tmp/codalab/tmph4mOac/run/program/score.py", line 30, in get_score
    exit(1)
  File "/usr/lib64/python3.6/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/codalab/tmph4mOac/run/program/score.py", line 54, in 
    raise Exception('Error in calculation of the specific score of the task')
Exception: Error in calculation of the specific score of the task

**Comment by apresunreve** [comment]
donno why it's just fixed

**Comment by thibault20cent** [comment]
I have the same issue. Model passes demo_feat.py but fails with above error in test. Any solution ?

**Comment by WebFace260M** [comment]
You should use the latest code of this repo.

**Comment by thibault20cent** [comment]
> You should use the latest code of this repo.

I do
