### ISSUE TITLE
Baseline performance comparison

### ISSUE THREAD

**Issue by cxz1418** [WebFace260M/webface260m-iccv21-mfr#5]
![image](https://user-images.githubusercontent.com/11434363/125907598-3420e10c-71c2-4434-938c-7c2d302451e7.png)

HI
As the second step during data set acquisition, it says that the entire set(260M) will be provided if the baseline is exceeded.
I would like to know how the comparison is made for Resnet50.
Is the baseline number listed in CodaLab an official number?
![image](https://user-images.githubusercontent.com/11434363/125907773-5fc03382-f79f-4840-9cf2-a177acf0173f.png)

And does it have to outperform in all fields to be provided?(Wild,Controlled...)

Thank you

**Comment by zhujiagang** [comment]
The first metric: All-Masked (MFR)
